### ISSUE TITLE
Can't join youtube channel to get repos of amd processors

### ISSUE THREAD

**Issue by casioforever** [luchina-gabriel/BASE-EFI-AMD-RYZEN-THREADRIPPER-PUBLIC#1]
how can i get 0.9.5 releases of these repos ?
https://github.com/luchina-gabriel/BASE-EFI-AMD-RYZEN-THREADRIPPER-PUBLIC
https://github.com/luchina-gabriel/BASE-EFI-AMD-BULLDOZER-FX-PROCESSORS-PUBLIC

**Comment by luchina-gabriel** [comment]
Hi @casioforever, the instructions are at the beginning of the repository (header). 

You must be a member of the channel and link your Discord account to the same YouTube account to view the #efi-base channel.

or, If you are a student on our course.
https://hackintosh.one/s/curso
